name: 'Build and Push Docker Image'
description: 'Action to build a Docker image and push it to the GitHub Packages'
inputs:
  version:
    description: 'The version tag for the Docker image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/asn-website:${{ inputs.version }} .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/asn-website:${{ inputs.version }}
