name: Publish Docker Image

on:
  workflow_dispatch: # Allows manual dispatch

permissions:
  packages: write # Add permissions for the token to access packages
  contents: write # Allow pushing Docker images

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history including tags

      - name: Get latest tag version
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LATEST_TAG" ]; then
            NEW_VERSION="1.0.0"
            echo "No tags found, starting at version $NEW_VERSION"
          else
            echo "Latest tag: $LATEST_TAG"
            IFS='.' read -r major minor patch <<< "${LATEST_TAG//v/}"
            patch=$((patch + 1))
            NEW_VERSION="$major.$minor.$patch"
            echo "New version: $NEW_VERSION"
          fi
          echo "::set-output name=new_version::v$NEW_VERSION"

      - name: Run custom action to build and push Docker image
        uses: ./.github/actions/build-and-push-image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          version: ${{ steps.get_tag.outputs.new_version }}

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git tag ${{ steps.get_tag.outputs.new_version }}
          git push origin ${{ steps.get_tag.outputs.new_version }}
